---
# - hosts: all
#   tasks:
#     - include: ci-cd/dep.yml
#       tags: [ci-cd]
#     - include: auto-scaling/dep.yml
#       tags: [auto-scaling]
#     - include: blue-green-deployment/dep.yml
#       tags: [blue-green-deployment]
#     - include: liveness-readiness/dep.yml
#       tags: [liveness-readiness]
#     - include: hexboard/dep.yml
#       tags: [hexboard]
#     - include: ab-testing/dep.yml
#       tags: [ab-testing]
- hosts: master
  tasks:
    - include: ab-testing/main.yml
      tags: [ab-testing]
    - include: auto-scaling/main.yml
      tags: [auto-scaling]
    - include: blue-green-deployment/main.yml
      tags: [blue-green-deployment]
    - include: ci-cd/main.yml
      tags: [ci-cd]
    - include: hexboard/main.yml
      tags: [hexboard]
    - include: job/main.yml
      tags: [job]
    - include: liveness-readiness/main.yml
      tags: [liveness-readiness]
    - include: quota-limits/main.yml
      tags: [quota]
    - include: security/main.yml
      tags: [security]
    - include: sti/main.yml
      tags: [sti]
