apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /exports/gogs
    server: ose-master
